import { useState } from "react";
import { decryptPayload, EncrypterError } from "@encrypter/crypto-core";
import { zipSync, type Zippable } from "fflate";
import { DropZone } from "./components/DropZone";
import { PasswordInput } from "./components/PasswordInput";
import { ProgressBar } from "./components/ProgressBar";
import { useAsync } from "./hooks/useAsync";
import { useActivity } from "./hooks/useActivity";
import { downloadBlob, formatBytes, readFileAsBytes } from "./utils";
import { mapEncrypterError } from "./EncryptPage";

export function DecryptPage() {
  const [encFile, setEncFile] = useState<File | null>(null);
  const [password, setPassword] = useState("");
  
  const { addActivity, savePasswords, setSavePasswords } = useActivity();
  const { loading, error, progress, run, reset } = useAsync<void>();

  const canDecrypt = encFile !== null && password.length >= 1 && !loading;

  const handleDecrypt = () => {
    if (!encFile || !canDecrypt) return;

    run(async (onProgress: (p: number) => void) => {
      onProgress(10);
      const encData = await readFileAsBytes(encFile);
      onProgress(30);

      let result;
      try {
        result = await decryptPayload(encData, password);
      } catch (err) {
        throw new Error(mapEncrypterError(err));
      }

      onProgress(70);

      const isSecureName = encFile.name !== result.metadata.originalName && encFile.name.startsWith("enc_");

      if (result.metadata.contentType === "folder" && result.folderEntries) {
        const archive: Zippable = {};
        const folderName = result.folderName || result.metadata.originalName;
        for (const entry of result.folderEntries) {
          archive[`${folderName}/${entry.path}`] = entry.data;
        }
        const zipData = zipSync(archive);
        downloadBlob(
          new Blob([zipData as any], { type: "application/zip" }),
          `${folderName}.zip`
        );
        
        // Log activity
        await addActivity(folderName, "decrypt", "folder", result.metadata.uncompressedSize, isSecureName, password);
      } else if (result.fileData) {
        const name = result.metadata.originalName;
        const mime = result.metadata.mimeType || "application/octet-stream";
        downloadBlob(new Blob([result.fileData as any], { type: mime }), name);
        
        // Log activity
        await addActivity(name, "decrypt", "file", result.metadata.uncompressedSize, isSecureName, password);
      } else {
        throw new EncrypterError("No data in decrypted file", "CORRUPTED");
      }

      onProgress(100);
    }).catch(() => {});
  };

  const handleReset = () => {
    setEncFile(null);
    setPassword("");
    reset();
  };

  return (
    <section className="panel animate-fade-in">
      <div className="panel__title-area">
        <h2>Decrypt Your Files</h2>
        <p className="panel__subtitle">Restore your encrypted files or folders using the correct password</p>
      </div>

      <DropZone
        accept=".enc,application/octet-stream"
        label="DROP YOUR .ENC FILE HERE OR CLICK TO BROWSE"
        hint="Encrypted file generated by Securitas"
        onFiles={(picked) => setEncFile(picked[0] ?? null)}
        disabled={loading}
      />

      {encFile && (
        <div className="file-info">
          <p>
            <strong>{encFile.name}</strong> — {formatBytes(encFile.size)}
          </p>
        </div>
      )}

      <PasswordInput
        password={password}
        onPasswordChange={setPassword}
        disabled={loading}
      />

      <div className="settings-options">
        <label className="toggle-label">
          <input
            type="checkbox"
            checked={savePasswords}
            onChange={(e) => setSavePasswords(e.target.checked)}
            className="toggle-checkbox"
            disabled={loading}
          />
          <span className="toggle-switch" />
          <span className="toggle-text">
            <strong>Save Password in Activity Log</strong>
            <span className="toggle-hint">Locally encrypted under a browser-unique key and stored only on this device</span>
          </span>
        </label>
      </div>

      {loading && (
        <ProgressBar value={progress} label="Decrypting files…" />
      )}

      {error && <p className="error-msg">{error}</p>}

      <div className="actions">
        <button
          type="button"
          className="btn btn--primary decrypt-btn"
          disabled={!canDecrypt}
          onClick={handleDecrypt}
        >
          {loading ? "Decrypting…" : "DECRYPT & DOWNLOAD 🔓"}
        </button>
        {(encFile || password) && (
          <button
            type="button"
            className="btn btn--ghost"
            onClick={handleReset}
            disabled={loading}
          >
            Clear
          </button>
        )}
      </div>

      <p className="tip">
        Folders are downloaded as a <code>.zip</code> file — extract it to recover
        the original folder structure.
      </p>
    </section>
  );
}
